FX_ACCOUNT_ID = '101-004-30581840-001'
FX_API_KEY = 'a856b96f70cfe8fc507765857fa98b56-94e46be1ae266b09fa59fb259ec9dcd5'
FX_API_URL = 'https://api-fxpractice.oanda.com' # https://api-fxtrade.oanda.com (live)
FX_ENVIRONMENT = 'practice' # "live" for live environment
FX_GOOGLE_APP_PASSWORD_FILE_PATH = '/Users/ralph/Library/CloudStorage/GoogleDrive-ralph.brecheisen@gmail.com/My Drive/data/ApiKeysAndPasswordFiles/google-forexscanner-app-password.txt'
FX_GMAIL_SMTP_HOST = 'smtp.gmail.com'
FX_GMAIL_SMPT_PORT = 465
FX_GMAIL_FROM = 'ralph.brecheisen@gmail.com'
FX_GMAIL_TO = 'r.brecheisen@maastrichtuniversity.nl'